### ISSUE TITLE
loan recash

### ISSUE THREAD

**Issue by Darnleybegue** [righen/LaFerme#3]
Error: System.NullReferenceException: Object reference not set to an instance of an object. at CCUALBARAKAHV1.BusinessLayer.checkOffProcessing.saveReceiptAndLoanRepaymentForRecash(ReceiptHeader receiptHeader, Dictionary`2 receiptDetailsData, Dictionary`2 receiptRepaymentData) at CCUALBARAKAHV1.BusinessLayer.LoanRepaymentCashProcessing.process(List`1 loanRepaymentCashList

**Comment by righen** [comment]
It was due to anti-forgery token.Solved
